/* @generated */

/* eslint-disable perfectionist/sort-objects */
export default {
  '#fffefc': 'var(--sc-editor-background)',
  '#FFE792': 'var(--sc-editor-findmatchbackground)',
  '#FFE79250': 'var(--sc-editor-findmatchhighlightbackground)',
  '#111111': 'var(--sc-editor-foreground)',
  '#C2E8FF30': 'var(--sc-editor-inactiveselectionbackground)',
  '#A5A5A520': 'var(--sc-editor-linehighlightbackground)',
  '#C2E8FF': 'var(--sc-editor-selectionbackground)',
  '#C2E8FF50': 'var(--sc-editor-selectionhighlightbackground)',
  '#284181': 'var(--sc-editorbrackethighlight-foreground2)',
  '#626FC9': 'var(--sc-editorbrackethighlight-foreground3)',
  '#352DE3': 'var(--sc-editorbrackethighlight-foreground4)',
  '#BB28C7': 'var(--sc-editorbrackethighlight-foreground5)',
  '#CD3131': 'var(--sc-editorbrackethighlight-unexpectedbracket-foreground)',
  '#3B68FC': 'var(--sc-editorcursor-foreground)',
  '#ADADAD': 'var(--sc-editorlinenumber-foreground)',
  '#E0E0E0': 'var(--sc-editorwhitespace-foreground)',
  '#3D87F5': 'var(--sc-focusborder)',
  '#0066BF': 'var(--sc-list-focushighlightforeground)',
  '#919191': 'var(--sc-comments-fg)',
  '#BC670F': 'var(--sc-comments-documentation-fg)',
  '#FFFDF7': 'var(--sc-comments-documentation-bg)',
  '#FFFFFF': 'var(--sc-invalid-deprecated-fg)',
  '#990000': 'var(--sc-invalid-deprecated-bg)',
  '#C56E0E': 'var(--sc-types-fg)',
  '#F93232': 'var(--sc-exceptions-fg)',
  '#DD3C2F': 'var(--sc-numbers-fg)',
  '#00A33F': 'var(--sc-strings-fg)',
  '#FBE9AD44': 'var(--sc-strings-escape-sequences-bg)',
  '#699D36': 'var(--sc-strings-regular-expressions-fg)',
  '#E8FFD5': 'var(--sc-strings-symbols-bg)',
  '#444444': 'var(--sc-object-keys-fg)',
  '#434343': 'var(--sc-embedded-source-fg)',
  '#7F7F7F': 'var(--sc-html-doctype-declaration-fg)',
  '#0072C8': 'var(--sc-html-tags-fg)',
  '#4F9FCF': 'var(--sc-html-tag-punctuation-fg)',
  '#3A77BF': 'var(--sc-css-selectors-fg)',
  '#43A202': 'var(--sc-css-property-values-fg)',
  '#FFFFDD': 'var(--sc-markup-changed-bg)',
  '#FFDDDD': 'var(--sc-markup-deletion-bg)',
  '#DDFFDD': 'var(--sc-markup-insertion-bg)',
  '#555555': 'var(--sc-markup-prompt-fg)',
};
